# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build Trovatore (macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14]
        dc: [ldc-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Build & Test'
      run: |
        dub build --compiler=$DC --build=release-nobounds

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trovatore-${{ matrix.os }}
        path: trovatore

    - name: Upload to Dropbox
      uses: Lewuathe/dropbox-github-action@v1
      with:
        dropbox-app-key: ${{ secrets.DROPBOX_APP_KEY }}
        dropbox-app-secret: ${{ secrets.DROPBOX_APP_SECRET }}
        dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        source-path: trovatore
        target-path: /release/macos-${{ runner.arch }}/trovatore
