name: Build Trovatore (linux-static)

on:
  push:
    branches:
      - main

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker build
    - name: Build Docker image
      run: |
        echo "FROM alpine:latest
        RUN apk add vim gcc musl-dev ldc dub llvm-libunwind-static openssl-libs-static gzip upx cmake make
        WORKDIR /app
        COPY . .
        CMD [\"dub\", \"build\", \"--build=release-nobounds\", \"--config=trovatore-static\"]" > Dockerfile
        docker build -t trovatore-image .

    # Run the Docker container to build the project
    - name: Run Docker container and build project
      run: |
        docker run --name trovatore-container trovatore-image || true

    # Copy compiled file from Docker container to host
    - name: Copy compiled binary
      run: |
        docker cp trovatore-container:/app/trovatore .
        docker rm trovatore-container
        strip -s trovatore

    # Upload the binary as an artifact
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trovatore
        path: trovatore

    - name: Upload to Dropbox
      uses: Lewuathe/dropbox-github-action@v1
      with:
        dropbox-app-key: ${{ secrets.DROPBOX_APP_KEY }}
        dropbox-app-secret: ${{ secrets.DROPBOX_APP_SECRET }}
        dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        source-path: trovatore
        target-path: /linux/trovatore
